server:
  port: 8082

spring:
  dubbo:
    application:
      name: server
#      logger: slf4j
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.rrww.dubboserver.Service

logging:
  level:
    com.rrww.dubboserver.Service: warn
#  pattern:
#    console:  %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
#    file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n


#配置日志
#logging:
  #配置日志文件路径
#  file: logs/aa.log
#  level:
#    com.rrww.dubboserver: debug #不同目录下的日志可配置不同级别
#    org.springfromework.web: info
#    org.hibernate: info
#  pattern:
#    console: %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${spring.dubbo.application.name}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}